# Generated by Django 4.1.7 on 2023-05-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_user_designation_profile_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedIn',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
