# Generated by Django 4.1.7 on 2023-04-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='frond_pic',
            field=models.ImageField(blank=True, null=True, upload_to='publications/image'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='publications/pdf'),
        ),
    ]
