# Generated by Django 4.1.7 on 2023-04-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='category',
        ),
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ManyToManyField(to='journals.category'),
        ),
    ]
