# Generated by Django 4.1.7 on 2023-05-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_remove_publication_category_publication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='front_pic',
            field=models.ImageField(blank=True, null=True, upload_to='publications/image'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='publications/pdf'),
        ),
    ]
