# Generated by Django 4.1.7 on 2023-05-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_publication_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authorship',
        ),
    ]
